export enum Languages {
  ENGLISH = 'English',
  FRENCH = 'French',
  SPANISH = 'Spanish',
  GERMAN = 'German',
  ITALIAN = 'Italian',
  SWEDISH = 'Swedish',
  POLISH = 'Polish',
  MANDARIN = 'Mandarin',
  KOREAN = 'Korean',
  JAPANESE = 'Japanese',
  HINDI = 'Hindi',
  BENGALI = 'Bengali',
  PORTUGUESE = 'Portoguese',
  RUSSIAN = 'Russian',
  Dutch = 'Dutch',
}
