import { Community } from '_types/Community';

export const privateCommunities: Community[] = [
  { id: 'doodles', image: 'assets/doodles.png', name: 'Doodles', isOwnedByUser: false, collectionIds: ['doodles'] },
  { id: 'coolcats', image: 'assets/coolcat.png', name: 'Cool Cats', isOwnedByUser: false, collectionIds: ['coolcats'] },
  {
    id: 'thechimpions',
    image: 'assets/chimpions.png',
    name: 'The Chimpions',
    isOwnedByUser: false,
    collectionIds: ['thechimpions'],
  },
  {
    id: 'boredapeyachtclub',
    image: 'assets/boredapeyachtclub.png',
    name: 'Bored Ape Yacht Club',
    isOwnedByUser: false,
    collectionIds: ['boredapeyachtclub'],
  },
  {
    id: 'cyberkongz',
    image: 'assets/cyberkongz.png',
    name: 'CyberKongz',
    isOwnedByUser: false,
    collectionIds: ['cyberkongz'],
  },
  {
    id: 'neotokyocitizens',
    image: 'assets/neotokyo.png',
    name: 'Neo Tokyo Citizens',
    isOwnedByUser: false,
    collectionIds: ['neotokyocitizens', 'neotokyooutercitizens'],
  },
  {
    id: 'veefriends',
    image: 'assets/veefriends.png',
    name: 'Veefriends',
    isOwnedByUser: false,
    collectionIds: ['veefriends'],
  },
  {
    id: 'worldofwomen',
    image: 'assets/worldofwomen.png',
    name: 'World of Women',
    isOwnedByUser: false,
    collectionIds: ['worldofwomen'],
  },
  { id: 'degods', image: 'assets/degods.png', name: 'Degods', isOwnedByUser: false, collectionIds: ['degods'] },
  {
    id: 'famousfoxfederation',
    image: 'assets/famousfoxfederation.png',
    name: 'Famous Fox Federation',
    isOwnedByUser: false,
    collectionIds: ['famousfoxfederation'],
  },
  {
    id: 'solanamonkeybusiness',
    image: 'assets/solanamonkeybusiness.png',
    name: 'Solana Monkey Business',
    isOwnedByUser: false,
    collectionIds: ['solanamonkeybusiness'],
  },
  {
    id: 'degenerateapeacademy',
    image: 'assets/degenerateapeacademy.png',
    name: 'Degenerate Ape Academy',
    isOwnedByUser: false,
    collectionIds: ['degenerateapeacademy'],
  },
  {
    id: 'sappyseals',
    image: 'assets/sappyseals.png',
    name: 'Sappy Seals',
    isOwnedByUser: false,
    collectionIds: ['sappyseals'],
  },
  { id: 'azuki', image: 'assets/azuki.png', name: 'Azuki', isOwnedByUser: false, collectionIds: ['azuki'] },
];
